---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
  SlackBotAuthToken:
    Type: String
    NoEcho: true

Globals:
  Function:
    CodeUri: dist/
    Runtime: go1.x
    Timeout: 30
    Tracing: Active
    Environment:
      Variables:
        STAGE: !Ref Stage

Resources:
  SlackBotHandlerFunction:
    Properties:
      CodeUri: dist/
      FunctionName: !Sub ${AWS::StackName}-SlackBotHandlerFunction
      Handler: slackbothandler
      Runtime: go1.x
      Policies:
        - Statement:
            - Action:
                - lambda:InvokeFunction
              Effect: Allow
              Resource: !GetAtt SlackBotWorkerFunction.Arn
          Version: 2012-10-17
      Events:
        Request:
          Properties:
            Method: POST
            Path: /slackbot
          Type: Api
      Timeout: 30
      Environment:
        Variables:
          SLACKBOT_WORKER_FUNCTION_NAME: !Ref SlackBotWorkerFunction
          SLACKBOT_AUTH_TOKEN: !Ref SlackBotAuthToken
    Type: AWS::Serverless::Function

  SlackBotWorkerFunction:
    Properties:
      CodeUri: dist/
      FunctionName: !Sub ${AWS::StackName}-SlackBotWorkerFunction
      Handler: slackbotworker
      Runtime: go1.x
      Timeout: 120
    Type: AWS::Serverless::Function

Outputs:
  APIEndpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApiProdStage}"
